# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-oZTkepLfUy-IMzH-WKtElXsavmVjOs
"""

import yfinance as yf
import streamlit as st

st.title("""간단한 주식 차트 증가(clossing price)와 거래량 (volume) 보기 - 테슬라""")
Stock_Symbol = 'TSLA'
StockData = yf.Ticker(Stock_Symbol)
StockChart = StockData.history(period = '1d', start='2019-7-1', end='2020-8-11')
st.line_chart(StockChart.Close)
st.line_chart(StockChart.Volume)